version: "3.9"
services:
  dictup-api:
    build: .
    environment:
      - DICTUP_DATASOURCE_MONGO_HOST=mongodb
      - DICTUP_DATASOURCE_MONGO_PORT=27017
      - DICTUP_DATASOURCE_MONGO_DATABASE=dictup
      - DICTUP_DATASOURCE_MONGO_USERNAME=dictup
      - DICTUP_DATASOURCE_MONGO_PASSWORD=dictup
      - DICTUP_SERVER_PORT=8080
      - DICTUP_SERVER_SECURITY_GOOGLEOAUTH2_CONFIG_CLIENTID=
      - DICTUP_SERVER_SECURITY_GOOGLEOAUTH2_CONFIG_CLIENTSECRET=
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0.2
    environment:
      - MONGO_INITDB_DATABASE=dictup
      - MONGO_INITDB_ROOT_USERNAME=dictup
      - MONGO_INITDB_ROOT_PASSWORD=dictup
    volumes:
      - ~/.mongodb-data:/data/db
    ports:
      - "27018:27017"