app:
  profile: dev
logger:
  level: info
server:
  host: ""
  port: 8080
  security:
    apiKeyAuth:
      accessTokenMaxAgeMin: 3600
      refreshTokenMaxAgeMin: 3601
    googleOAuth2:
      config:
        clientID: "some clientID from env"
        clientSecret: "some clientSecret from env"
        redirectURL: "http://dictup.com:8080/auth/google/callback"
        scopes:
          - "https://www.googleapis.com/auth/userinfo.email"
          - "https://www.googleapis.com/auth/userinfo.profile"
        endpoint:
          authURL: "https://accounts.google.com/o/oauth2/auth"
          tokenURL: "https://oauth2.googleapis.com/token"
          authStyle: 1
      userInfoURL: "https://www.googleapis.com/oauth2/v2/userinfo?access_token="
      redirectOnErrorURL: "/"
    cors:
      allowOrigin: "*"
      allowMethods: "*"
      allowHeaders: "*"
datasource:
  mongo:
    host: localhost
    port: 27017
    database: dictup
    username:
    password:
