app:
  profile: dev
logger:
  level: info
server:
  host: localhost
  port: 8080
  security:
    apiKeyAuth:
      accessTokenMaxAgeMin: 3600
      refreshTokenMaxAgeMin: 3601
datasource:
  mongo:
    host: localhost
    port: 27017
    schema: dictup
